= Quickstart

These steps will get you up and going with using Pkl and Swift.

== 1. Install dependencies

Add the pkl-swift library as a dependency to your project's `Package.swift`:

.Package.swift
[source,swift]
[subs="+attributes"]
----
let package = Package(
    dependencies: [
        .package(url: "https://github.com/apple/pkl-swift", from: "{version}")
    ],
    targets: [
        .executableTarget(
            name: "my-application",
            dependencies: [.product(name: "PklSwift", package: "pkl-swift")]
        ),
    ]
)
----

Also, ensure that Pkl is xref:main:pkl-cli:index.adoc#installation[installed on your machine].

== 2. Define a Pkl schema

Create a new Pkl file in the directory of your choice, to describe the schema of your configuration.
In this example, the file is placed into `pkl/AppConfig.pkl`.

.pkl/AppConfig.pkl
[source,pkl]
----
module AppConfig

/// The hostname of this application.
host: String

/// The port to listen on.
port: UInt16
----

[#codegen]
== 3. Generate Swift source code

With a schema defined, generate Swift source code for it.
Code generation is done via the `gen.pkl` CLI tool inside the `pkl.swift` package.

In our example, Swift sources can be generated using the following command:

[source,bash]
----
pkl run package://pkg.pkl-lang.org/pkl-swift/pkl.swift@{version}#/gen.pkl pkl/AppConfig.pkl -o Sources/MyApplication/Generated/
----

If using xref:main:language-reference:index.adoc#projects[a `PklProject`] to manage the `pkl.swift` dependency, the tool's URI may be replaced with dependency notation:

[source,bash]
----
pkl run @pkl.swift/gen.pkl pkl/AppConfig.pkl -o Sources/MyApplication/Generated/
----

This will create a file called `AppConfig.pkl.swift` inside the `Sources/MyApplication/Generated` directory.

For more details on how to control code generation, consult the CLI help:

[source,bash]
----
pkl run @pkl.swift/gen.pkl --help
----

== 4. Evaluate Pkl configuration data in Swift

With the above scaffolding set up, evaluate Pkl configuration data in Swift.

First, define some configuration that uses the Pkl schema.

In our example, we create a file at path `pkl/local/appConfig.pkl`. We imagine that we are defining configuration for a server running in a local environment, and would likewise place other environments in sibling directorys; e.g. `pkl/int/appConfig.pkl` and `pkl/prod/appConfig.pkl`.

.pkl/local/appConfig.pkl
[source,pkl]
----
amends "../AppConfig.pkl"

host = "localhost"

port = 5939
----

Once defined, evaluate the Pkl module into Swift data.

.Sources/MyApplication/Main.swift
[source,swift]
----
func main() async throws {
	let config = try await AppConfig.loadFrom(source: .path("pkl/local/appConfig.pkl"))
	print("I'm running on host \(config.host)\n")
}
----
